name: Auto Tag & Release

on:
  push:
    branches:
      - main

jobs:
  tag-and-release:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Git user
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Get latest tag
        id: get_tag
        run: |
          git fetch --tags
          latest_tag=$(git tag --sort=-v:refname | grep -E '^v[0-9]+\.[0-9]+\.[0-9]+$' | head -n1)
          if [ -z "$latest_tag" ]; then
            echo "latest_tag=v0.0.0" >> $GITHUB_OUTPUT
          else
            echo "latest_tag=$latest_tag" >> $GITHUB_OUTPUT
          fi

      - name: Bump patch version and create tag
        id: bump_tag
        run: |
          old_tag="${{ steps.get_tag.outputs.latest_tag }}"
          IFS='.' read -r major minor patch <<<"${old_tag#v}"
          patch=$((patch + 1))
          new_tag="v${major}.${minor}.${patch}"
          git tag "$new_tag"
          git push origin "$new_tag"
          echo "new_tag=$new_tag" >> $GITHUB_OUTPUT

      - name: Create tarball
        run: |
          mkdir artefacts
          tar --exclude=.git --exclude=./artefacts -cvzf artefacts/gh-docker-compose-monitor.tar.gz .

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.bump_tag.outputs.new_tag }}
          name: Release ${{ steps.bump_tag.outputs.new_tag }}
          body: |
            Automated release for ${{ steps.bump_tag.outputs.new_tag }}
          files: artefacts/gh-docker-compose-monitor.tar.gz