name: Auto Tag & Release

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Lint & Quality Checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run ShellCheck on all shell scripts
        uses: azohra/shellcheck-action@v0.8.0
        with:
          path: 'common'

      - name: Lint workflow YAML files
        uses: ibiqlik/action-yamllint@v3
        with:
          file_or_dir: .github/workflows

  tag-and-release:
    name: Tag, Package, and Release
    runs-on: ubuntu-latest
    needs: lint
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Git user
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Get latest tag
        id: get_tag
        run: |
          git fetch --tags
          latest_tag=$(git tag --sort=-v:refname | grep -E '^v[0-9]+\.[0-9]+\.[0-9]+$' | head -n1)
          if [ -z "$latest_tag" ]; then
            echo "latest_tag=v0.0.0" >> $GITHUB_OUTPUT
          else
            echo "latest_tag=$latest_tag" >> $GITHUB_OUTPUT
          fi

      - name: Bump patch version
        id: bump_tag
        run: |
          old_tag="${{ steps.get_tag.outputs.latest_tag }}"
          IFS='.' read -r major minor patch <<<"${old_tag#v}"
          patch=$((patch + 1))
          new_tag="v${major}.${minor}.${patch}"
          echo "new_tag=$new_tag" >> $GITHUB_OUTPUT

      - name: Update script version for release
        run: |
          sed -i "s/^SCRIPT_VERSION=.*/SCRIPT_VERSION=\"${{ steps.bump_tag.outputs.new_tag }}\"/" common/compose-deploy.sh
          git add common/compose-deploy.sh
          git commit -m "Release ${{ steps.bump_tag.outputs.new_tag }}: set script version"

      - name: Create and push tag
        run: |
          git tag "${{ steps.bump_tag.outputs.new_tag }}"
          git push origin "${{ steps.bump_tag.outputs.new_tag }}"

      - name: Create tarball
        run: |
          mkdir artefacts
          tar --exclude=.git --exclude=./artefacts -cvzf artefacts/gh-docker-compose-monitor.tar.gz .

      - name: Verify tarball contents
        run: |
          tar -tzf artefacts/gh-docker-compose-monitor.tar.gz | grep common/compose-deploy.sh

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.bump_tag.outputs.new_tag }}
          name: Release ${{ steps.bump_tag.outputs.new_tag }}
          body: |
            Automated release for ${{ steps.bump_tag.outputs.new_tag }}
          files: artefacts/gh-docker-compose-monitor.tar.gz